# Generated by Django 2.0.6 on 2018-06-20 22:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180616_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 20, 22, 57, 16, 320294, tzinfo=utc)),
        ),
    ]
